language: node_js
node_js:
  - 8
os: osx
before_install:
  - npm install -g node-gyp
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  slack: inclusive-tech:PNqRn3KSBfboII6OvVvOzl5w